### ISSUE TITLE
Jest hangs at "testing changes"

### ISSUE THREAD

**Issue by morungos** [orta/vscode-jest#195] opened 2017-12-13 22:43 UTC
### Environment

1. `node -v`: `v6.12.0`
2. `npm -v`: `3.10.10`
3. `node node_modules/.bin/jest --version`: `v21.2.1`
4. `npm ls react-scripts` (if you haven’t ejected): `NA, no React etc.`

1. Operating system: `macOS 10.13.2`

### Steps to Reproduce

None. It happens out of the box. Strangely, I have another system, with virtually identical setup (save Node `v6.12.2`) which doesn't have a problem with Jest hanging. I'll bring the versions into exact line and confirm status if different. So there is definitely an environment/setup/config issue causing different behaviour. 

### Expected Behavior

Jest completes. 

### Actual Behavior

Jest does it's initial scan, then mentions "watch mode", then spins at "testing changes". Essentially it's indistinguishable from #128, but without the errors. Jest completes its tests both the initial and the later ones successfully, but VSCode is wedged on "testing changes". 

There's also a process listed:

```
  PID TTY           TIME CMD
65124 ??         0:02.67 node node_modules/.bin/jest --json --useStderr --outputFile /var/folders/p7/sfg0k3392314nk2m5vnbm2nc0000gn/T/jest_runner.json --watch
```

When run manually, this ends correctly at the "Watch Usage" menu. 

The behaviour appears cosmetic. Future changes and edits are detected, and re-run the tests. It's just the front end hides that by showing, in one environment, the spinning "testing changes" in the status bar. 

No funny DB code or anything else: this isn't React, or a complex app, it's a straight JS library.

**Comment by morungos** [comment] 2017-12-13 23:15
Hmmm, it seems to have stabilized and fixed itself. Which is weird. There must have been some state which wasn't cleared right. It was also marking, for a while, there being errors in Jest when there weren't, and even when all tests passed.

**Comment by seanpoulter** [comment] 2017-12-14 03:54
Thanks for taking the time to report the issue @morungos. That sounds like some strange behavior!

I'm closing the issue since we can't reproduce the problem but please re-open as necessary. I've found the easiest way to troubleshoot issues is debugging the extension and opening a minimal repo that reproduces the problem. Since this may be more machine or configuration specific, you might need to take a look on your end starting with the steps in [this comment](https://github.com/orta/vscode-jest/issues/128#issuecomment-351598609). I'm happy to help investigate if we get to that point.

**Closed by seanpoulter** 2017-12-14 03:54 UTC
Labels: bug, needs more info
